### ISSUE TITLE
How does hunspell works

### ISSUE THREAD

**Issue by rezvannzri** [hunspell/hunspell.github.io#8]
I looked for a paper which explains how does hunspell works, but without any success. I would like to know how does hunspell works and especially how does it make suggestions ? Does it uses Levenshtein distance to look for the best suggestion ?

**Comment by PanderMusubi** [comment]
@rezvannzri, it does indeed use Levenshtein distance but also several other mechanisms. Once Nuspell version 2.0 has been completed we can see how to document the general working of the software.
